package GUI;

import AdminSystem.AdministrationSystem;
import DataBaseControl.CredentialsDB;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JLabel();
        txtBadcreds = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdminLogin = new javax.swing.JButton();
        btnUserLogin = new javax.swing.JButton();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ATRAS.png"))); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAtrasMousePressed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtBadcreds.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtBadcreds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtBadcreds, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 300, 20));

        txtUserEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 370, 40));

        txtUserPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 370, 40));

        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jLabel1.setText("Correo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        btnAdminLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminLogin.setText("Administrador");
        btnAdminLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdminLoginMousePressed(evt);
            }
        });
        getContentPane().add(btnAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 120, 30));

        btnUserLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnUserLogin.setText("Ingresar");
        btnUserLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserLoginMousePressed(evt);
            }
        });
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 100, 30));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/INICIO-SESION.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserLoginMousePressed
        CredentialsDB dbConection;
        String dbPassword;
        
        String userEmail = txtUserEmail.getText();
        String userPassword = String.valueOf(txtUserPassword.getPassword());

        try {
            dbConection = new CredentialsDB();
            boolean isUserExist = dbConection.checkUserExistence(userEmail, CredentialsDB.usuarios);

            if (isUserExist) {
                dbPassword = dbConection.getUserPassword(userEmail, CredentialsDB.usuarios);

                if (dbPassword.equals(userPassword)) {
                    // Los datos son correctos
                    JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso.");
                    hide();
                    Home v1 = new Home();
                    v1.show();
                    // Opcionalmente puedes redirigir al usuario a otra pantalla
                } else {
                    // Las contraseñas no coinciden
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta. Por favor inténtalo de nuevo.");
                }
            } else {
                // El correo electrónico no existe en la base de datos
                JOptionPane.showMessageDialog(null, "El correo electrónico ingresado no existe. Por favor inténtalo de nuevo.");
            }
        } catch (Exception e) {
            // Manejo de excepciones
        }

    }//GEN-LAST:event_btnUserLoginMousePressed

    private void btnAdminLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminLoginMousePressed
        CredentialsDB dbConnection;
        String dbPassword;
        String userEmail = txtUserEmail.getText();
        String userPassword = String.valueOf(txtUserPassword.getPassword());

        try {
            dbConnection = new CredentialsDB();

            // Verificar si el usuario existe en la tabla de administradores
            boolean isUserExist = dbConnection.checkUserExistence(userEmail, CredentialsDB.administradores);

            if (isUserExist) {
                // Obtener la contraseña del usuario
                dbPassword = dbConnection.getUserPassword(userEmail, CredentialsDB.administradores);

                if (dbPassword.equals(userPassword)) {
                    JOptionPane.showMessageDialog(null, "Iniciando en el sistema de Administracion.");
                    dispose();
                    AdministrationSystem v1 = new AdministrationSystem();
                    v1.show();
                } else {
                    // Contraseña incorrecta, mostrar mensaje de error
                    txtBadcreds.setText("Credenciales incorrectas");
                }
            } else {
                // Usuario no existe, mostrar mensaje de error
                txtBadcreds.setText("Usuario no encontrado");
            }
        } catch (Exception e) {
            // Manejar la excepción
        }

    }//GEN-LAST:event_btnAdminLoginMousePressed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void btnAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMousePressed
        hide();
        InicioProyecto v1 = new InicioProyecto();
        v1.show();
    }//GEN-LAST:event_btnAtrasMousePressed

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtBadcreds;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
