/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminSystem;

import ControlBaseDatos.DBadminsystem;
import GUI.InicioProyecto;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Farg-
 */
public class AdministrationSystem extends javax.swing.JFrame {

    /**
     * Creates new form AdministrationSystem
     */
    public AdministrationSystem() {
        initComponents();
        cargarDatosFacturas();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDBprovedores = new javax.swing.JButton();
        btnDBempleados = new javax.swing.JButton();
        btnDBusuarios = new javax.swing.JButton();
        btnDBproductos = new javax.swing.JButton();
        btnDBviajes = new javax.swing.JButton();
        btnFacturaIndividual = new javax.swing.JButton();
        btnEliminarFactura = new javax.swing.JButton();
        btnModificarFactura = new javax.swing.JButton();
        btnAgregarFactura = new javax.swing.JButton();
        txtPrecioNeto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDescuentosApli = new javax.swing.JTextField();
        txtImpuestos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioBruto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMetodoPago = new javax.swing.JTextField();
        txtDetalles = new javax.swing.JTextField();
        txtEmision = new javax.swing.JTextField();
        txtNumFactura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFacturas = new javax.swing.JTable();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDBprovedores.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBprovedores.setText("DB Provedor");
        btnDBprovedores.setToolTipText("");
        btnDBprovedores.setBorder(null);
        btnDBprovedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBprovedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBprovedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 120, 40));

        btnDBempleados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBempleados.setText("DB Empleados");
        btnDBempleados.setToolTipText("");
        btnDBempleados.setBorder(null);
        btnDBempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBempleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 120, 40));

        btnDBusuarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBusuarios.setText("DB Usuarios");
        btnDBusuarios.setToolTipText("");
        btnDBusuarios.setBorder(null);
        btnDBusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBusuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 110, 40));

        btnDBproductos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBproductos.setText("DB Productos");
        btnDBproductos.setToolTipText("");
        btnDBproductos.setBorder(null);
        btnDBproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBproductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, 40));

        btnDBviajes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBviajes.setText("DB Viajes");
        btnDBviajes.setToolTipText("");
        btnDBviajes.setBorder(null);
        btnDBviajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBviajesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBviajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 110, 40));

        btnFacturaIndividual.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btnFacturaIndividual.setText("Factura Individual");
        btnFacturaIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaIndividualActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacturaIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 120, 40));

        btnEliminarFactura.setText("Eliminar");
        btnEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 120, 40));

        btnModificarFactura.setText("Modificar");
        btnModificarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 120, 40));

        btnAgregarFactura.setText("Agregar");
        btnAgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 120, 40));
        getContentPane().add(txtPrecioNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 200, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Precio Neto:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descuento Aplicado:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));
        getContentPane().add(txtDescuentosApli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 200, -1));
        getContentPane().add(txtImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 200, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Impuestos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));
        getContentPane().add(txtPrecioBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 200, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio Bruto:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));
        getContentPane().add(txtMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 200, -1));
        getContentPane().add(txtDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 200, -1));
        getContentPane().add(txtEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 200, -1));
        getContentPane().add(txtNumFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 200, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Metodo Pago:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Detalles:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Emision:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("# Factura:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Facturacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 20));

        TablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFacturas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 347, 910, 190));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administracion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LOGOBANNER.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/CERRAR-SESION.png"))); // NOI18N
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMousePressed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FONDO2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDBviajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBviajesActionPerformed
        DBflights v1 = new DBflights();
        v1.show();
    }//GEN-LAST:event_btnDBviajesActionPerformed

    private void btnDBproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBproductosActionPerformed
        DBproducts v2 = new DBproducts();
        v2.show();
    }//GEN-LAST:event_btnDBproductosActionPerformed

    private void btnDBusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBusuariosActionPerformed
        DBusers v3 = new DBusers();
        v3.show();
    }//GEN-LAST:event_btnDBusuariosActionPerformed

    private void btnDBempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBempleadosActionPerformed
        DBemployees v4 = new DBemployees();
        v4.show();
    }//GEN-LAST:event_btnDBempleadosActionPerformed

    private void btnDBprovedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBprovedoresActionPerformed
        DBproviders v5 = new DBproviders();
        v5.show();
    }//GEN-LAST:event_btnDBprovedoresActionPerformed

    private void btnAgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFacturaActionPerformed
        // codigo para agregar datos a la DB
        try {
            DBadminsystem  cc = new DBadminsystem ();
            Connection cn = cc.DBcontrolProductos();

            PreparedStatement ps = cn.prepareStatement("INSERT INTO facturacion VALUES (?,?,?,?,?,?,?,?);");

            int numero_factura = Integer.parseInt(txtNumFactura.getText());
            String fecha_emision = txtEmision.getText();
            String detalles = txtDetalles.getText();
            String metodo_pago = txtMetodoPago.getText();
            String precio_bruto = txtPrecioBruto.getText();
            String impuestos = txtImpuestos.getText();
            String descuentos_aplicados = txtDescuentosApli.getText();
            String precio_neto = txtPrecioNeto.getText();

            ps.setInt(1, numero_factura);
            ps.setString(2, fecha_emision);
            ps.setString(3, detalles);
            ps.setString(4, metodo_pago);
            ps.setString(5, precio_bruto);
            ps.setString(6, impuestos);
            ps.setString(7, descuentos_aplicados);
            ps.setString(8, precio_neto);
            ps.executeUpdate();

            limpiarCamposFacturas();
            cargarDatosFacturas();
            JOptionPane.showMessageDialog(null, "Datos guardados exitósamente!");

        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarFacturaActionPerformed

    private void btnModificarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarFacturaActionPerformed
        // Codigo para editar datos de la DB:
        try {
            DBadminsystem cc = new DBadminsystem();
            Connection cn = cc.DBcontrolProductos();

            PreparedStatement ps = cn.prepareStatement("UPDATE facturacion SET fecha_emision = ?, detalles = ?, metodo_pago = ?, precio_bruto = ?, impuestos = ?, descuentos_aplicados = ?, precio_neto = ? WHERE numero_factura = ?;");

            int numero_factura = Integer.parseInt(txtNumFactura.getText());
            String fecha_emision = txtEmision.getText();
            String detalles = txtDetalles.getText();
            String metodo_pago = txtMetodoPago.getText();
            String precio_bruto = txtPrecioBruto.getText();
            String impuestos = txtImpuestos.getText();
            String descuentos_aplicados = txtDescuentosApli.getText();
            String precio_neto = txtPrecioNeto.getText();

            
            ps.setString(1, fecha_emision);
            ps.setString(2, detalles);
            ps.setString(3, metodo_pago);
            ps.setString(4, precio_bruto);
            ps.setString(5, impuestos);
            ps.setString(6, descuentos_aplicados);
            ps.setString(7, precio_neto);
            ps.setInt(8, numero_factura);
            ps.executeUpdate();

            limpiarCamposFacturas();
            cargarDatosFacturas();
            JOptionPane.showMessageDialog(null, "Datos actualizados exitósamente!");

        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnModificarFacturaActionPerformed

    private void TablaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturasMouseClicked
        // seleccion de datos de la tabla para hacer CRUD:
        int fila = TablaFacturas.getSelectedRow();

        txtNumFactura.setText(TablaFacturas.getValueAt(fila, 0).toString());
        txtEmision.setText(TablaFacturas.getValueAt(fila, 1).toString());
        txtDetalles.setText(TablaFacturas.getValueAt(fila, 2).toString());
        txtMetodoPago.setText(TablaFacturas.getValueAt(fila, 3).toString());
        txtPrecioBruto.setText(TablaFacturas.getValueAt(fila, 4).toString());
        txtImpuestos.setText(TablaFacturas.getValueAt(fila, 5).toString());
        txtDescuentosApli.setText(TablaFacturas.getValueAt(fila, 6).toString());
        txtPrecioNeto.setText(TablaFacturas.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_TablaFacturasMouseClicked

    private void btnEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFacturaActionPerformed
        // Codigo para eliminar datos de la DB:
        try {
            DBadminsystem cc = new DBadminsystem();
            Connection cn = cc.DBcontrolProductos();

            PreparedStatement ps = cn.prepareStatement("DELETE FROM facturacion WHERE numero_factura = ?;");

            int numero_factura = Integer.parseInt(txtNumFactura.getText());

            ps.setInt(1, numero_factura);
            ps.executeUpdate();
            
            limpiarCamposFacturas();
            cargarDatosFacturas();
            JOptionPane.showMessageDialog(null, "Eliminado exitósamente!");

        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarFacturaActionPerformed

    private void btnFacturaIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaIndividualActionPerformed
        DBFactuIndividual v6 = new DBFactuIndividual();
        v6.show();
    }//GEN-LAST:event_btnFacturaIndividualActionPerformed

    private void btnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMousePressed
        hide();
        InicioProyecto v1 = new InicioProyecto();
        v1.show();
    }//GEN-LAST:event_btnCerrarSesionMousePressed

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited
    //METODO PARA CARGAR DATOS DE LA DB DE FACTURAS
    public void cargarDatosFacturas() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("# Factura");
            modelo.addColumn("FechaEmision");
            modelo.addColumn("Detalles");
            modelo.addColumn("MetodoPago");
            modelo.addColumn("PrecioBruto");
            modelo.addColumn("Impuestos");
            modelo.addColumn("Descuentos");
            modelo.addColumn("PrecioNeto");

            DBadminsystem cc = new DBadminsystem();
            Connection cn = cc.DBcontrolProductos();

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM facturacion");

            while (rs.next()) {
                String[] fila = new String[8];
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                fila[6] = rs.getString(7);
                fila[7] = rs.getString(8);
                modelo.addRow(fila);
            }
            TablaFacturas.setModel(modelo);

        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }
    
    //METODO PARA LIMPIAR CAMPOS EN LOS TXT DE FACTURAS
    public void limpiarCamposFacturas() {
        txtNumFactura.setText("");
        txtEmision.setText("");
        txtDetalles.setText("");
        txtMetodoPago.setText("");
        txtPrecioBruto.setText("");
        txtImpuestos.setText("");
        txtDescuentosApli.setText("");
        txtPrecioNeto.setText("");
        txtNumFactura.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrationSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFacturas;
    private javax.swing.JButton btnAgregarFactura;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JButton btnDBempleados;
    private javax.swing.JButton btnDBproductos;
    private javax.swing.JButton btnDBprovedores;
    private javax.swing.JButton btnDBusuarios;
    private javax.swing.JButton btnDBviajes;
    private javax.swing.JButton btnEliminarFactura;
    private javax.swing.JButton btnFacturaIndividual;
    private javax.swing.JButton btnModificarFactura;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDescuentosApli;
    private javax.swing.JTextField txtDetalles;
    private javax.swing.JTextField txtEmision;
    private javax.swing.JTextField txtImpuestos;
    private javax.swing.JTextField txtMetodoPago;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtPrecioBruto;
    private javax.swing.JTextField txtPrecioNeto;
    // End of variables declaration//GEN-END:variables
}
